### PR TITLE
Change "Modify" to "Update" to the type AuditedActions for clarity

### PR DESCRIPTION
**Pull request by jacqueline-homan**

### CODE REVIEW

**Comment by andredublin** [comment]
Doesn't modify indicate update?

**Comment by jeroldhaas** [comment]
I'd created the schema with `modify` to be synonymous with `update`. @jacqueline-homan is there a reason for having the two separate?

Perhaps for proper nomenclature, we should rename `modify` to `update` - thoughts?

**Comment by jacqueline-homan** [comment]
@jeroldhaas I think that changing the nomenclature from `modify` to `update` would clarify things because  in many cases, I've seen in other projects (not in F#) where `edit` or `modify` was actually different from `update` so if the schema was created with having `modify` and `update` to be one in the same, then a simple name change would do the trick.

**Comment by jeroldhaas** [comment]
I'm agreeable to that. If you like, then, @jacqueline-homan feel free to modify this PR with `modify` renamed to `update`, and I'll happily merge in the change. :smile:

**Comment by jacqueline-homan** [comment]
@jeroldhaas Done :)

**Pull request merged**
